name: Build and Push Internal App to Docker

on:
  push:
    paths:
      - internal/**
    branches:
      - main
env:
  DOCKER_ID:  ${{ secrets.DOCKER_HUB_USERNAME }}
  RUN_NUMBER: ${{ github.run_number }}
  IMAGE: internal

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: 'internal'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

   # Test
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install  
    - name: Run tests
      run: npm test
    
    # Login to docker hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push App
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./internal/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:v2.1.${{ github.run_number }}
